name: Continuous Integration

on:
  pull_request:
    branches:
      - dev
      - sit
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js version 18.x

      - name: Install Yarn
        run: npm install --global yarn@1.22.22  # Specify Yarn version 1.22.22

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run Lefthook CI checks
        run: yarn lefthook run ci-hook

      - name: Run tests
        run: yarn test-ci

      # Optional: Add a step for building the project (if applicable)
      # - name: Build Project
      #   run: yarn build

      # Optional: Add a step for running end-to-end tests (if applicable)
      # - name: Run End-to-End Tests
      #   run: yarn test:e2e  # Adjust command as necessary

      # Optional: Add a step for iOS build (requires macOS runner)
      # - name: Build iOS
      #   run: |
      #     cd ios
      #     pod install
      #     cd ..
      #     yarn run ios  # Adjust command as necessary
